In [45]:
!pip3 install paddlepaddle -i https://mirror.baidu.com/pypi/simple/

Looking in indexes: https://mirror.baidu.com/pypi/simple/, https://us-python.pkg.dev/colab-wheels/public/simple/


In [46]:
# git clone https://github.com/PaddlePaddle/PaddleOCR.git

In [47]:
!pip install paddlepaddle-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [48]:
!pip install paddleocr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [49]:
# Importing required functions for inference and visualization.
from paddleocr import PaddleOCR,draw_ocr 
import os
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
# ocr = PaddleOCR(use_angle_cls=True)

In [50]:
# from paddleocr import PaddleOCR,draw_ocr
# # Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# # You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# # to switch the language model in order.
# ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
# img_path = '/content/English_text.webp'
# result = ocr.ocr(img_path, cls=True)
# for line in result:
#      print(line)
# # draw result
# from PIL import Image
# image = Image.open(img_path).convert('RGB')
# boxes = [line[0] for line in result]
# txts = [line[1][0] for line in result]
# scores = [line[1][1] for line in result]
# im_show = draw_ocr(image, boxes, txts, scores, font_path='/content/PaddleOCR/doc/fonts/simfang.ttf')
# im_show = Image.fromarray(im_show)
# im_show.save('result.jpg')

In [51]:
from paddleocr import PaddleOCR,draw_ocr
ocr=PaddleOCR(lang="en")

[2022/08/09 22:22:00] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='f

In [52]:
image_path='/content/6-3.png'
image_cv=cv2.imread(image_path)
image_height=image_cv.shape[0]
image_width=image_cv.shape[1]
output=ocr.ocr(image_path)

[2022/08/09 22:22:00] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/08/09 22:22:01] ppocr DEBUG: dt_boxes num : 283, elapse : 0.2288970947265625
[2022/08/09 22:22:01] ppocr DEBUG: rec_res num  : 283, elapse : 0.5126409530639648


In [53]:
print(output)

[[[[645.0, 224.0], [1188.0, 229.0], [1188.0, 268.0], [644.0, 263.0]], ('KA', 0.7629125118255615)], [[[598.0, 275.0], [1220.0, 275.0], [1220.0, 307.0], [598.0, 307.0]], ('Xiamen Changsu Industrial Corporation Limited', 0.9942663311958313)], [[[529.0, 307.0], [1291.0, 309.0], [1291.0, 341.0], [529.0, 338.0]], ('ADD:No. 268 Wengjiao Road. Xinyang Industrial Zone, Haicang Xiamen. 361026 China', 0.9423612356185913)], [[[603.0, 348.0], [1210.0, 351.0], [1210.0, 378.0], [603.0, 375.0]], ('Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn', 0.9367617964744568)], [[[728.0, 387.0], [999.0, 387.0], [999.0, 421.0], [728.0, 421.0]], ('PACKING LIST', 0.9742295742034912)], [[[371.0, 436.0], [657.0, 436.0], [657.0, 460.0], [371.0, 460.0]], ('Messrs:Mag Data-S.p.A', 0.9582993388175964)], [[[866.0, 429.0], [1114.0, 429.0], [1114.0, 460.0], [866.0, 460.0]], ('Invoice No.: CS210746', 0.973578691482544)], [[[465.0, 455.0], [728.0, 458.0], [728.0, 490.0], [465.0, 487.0]], ('Strada della Selva 

In [54]:
boxes=[line[0] for line in output]
texts=[line[1][0] for line in output]
probabilities=[line[1][1] for line in output]

In [55]:
image_boxes=image_cv.copy()

In [56]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes,(int(box[0][0]),int(box[0][1])),(int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes,text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [57]:
cv2.imwrite('detections.jpg',image_boxes)

True

### Reconstruction 

In [58]:
im=image_cv.copy()

In [59]:
horiz_boxes=[]
vert_boxes=[]

for box in boxes:
  x_h,x_v=0,int(box[0][0])
  y_h,y_v=int(box[0][1]),0
  width_h,width_v=image_width,int(box[2][0]-box[0][0])
  height_h,height_v=int(box[2][1]-box[0][1]),image_height
                                    
  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h),(x_h+width_h,y_h+height_h),(255,255,0),1)
  cv2.rectangle(im,(x_v,y_v),(x_v+width_v,y_v+height_v),(255,255,0),1)

In [60]:
boxes[0]

[[645.0, 224.0], [1188.0, 229.0], [1188.0, 268.0], [644.0, 263.0]]

In [61]:
horiz_boxes[0]

[0, 224, 1653, 268]

In [62]:
cv2.imwrite('horiz_vert.jpg',im)

True

In [63]:
# cv2.imwrite('vert.jpg',im)

In [64]:
import tensorflow as tf
horiz_out=tf.image.non_max_suppression(horiz_boxes,
                                       probabilities,
                                       max_output_size=1000,
                                       iou_threshold=0.1,
                                       score_threshold=float('-inf'),
                                       name=None)

In [65]:
print(horiz_out)

tf.Tensor(
[201 174 213  94 281  99 153 205 186 232 220 194 265  31 272  44 176 258
 137 122 112  42  70 127 238  52  60  13 106 242  76 158 170  83 247 144
  23  29  11   8  10   1  20   4   6  15   2   3   0], shape=(49,), dtype=int32)


In [66]:
import numpy as np
horiz_lines=np.sort(np.array(horiz_out))
print(horiz_lines)

[  0   1   2   3   4   6   8  10  11  13  15  20  23  29  31  42  44  52
  60  70  76  83  94  99 106 112 122 127 137 144 153 158 170 174 176 186
 194 201 205 213 220 232 238 242 247 258 265 272 281]


In [67]:
in_nms=image_cv.copy()

In [68]:
for val in horiz_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(horiz_boxes[val][0]),int(horiz_boxes[val][1])),(int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [69]:
cv2.imwrite('im_nms.jpg',in_nms)

True

In [70]:
vert_out=tf.image.non_max_suppression(vert_boxes,
                                      probabilities,
                                      max_output_size=1000,
                                      iou_threshold=0.1,
                                      score_threshold=float('-inf'),
                                      name=None)

In [71]:
vert_lines=np.sort(np.array(vert_out))
print(vert_lines)

[ 13 191 194 201 205 213 265 272]


In [72]:
for val in vert_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(vert_boxes[val][0]),int(vert_boxes[val][1])),(int(vert_boxes[val][2]),int(vert_boxes[val][3])),(0,0,255),1)

In [73]:
cv2.imwrite('im_nms1.jpg',in_nms)

True

In [74]:
print(vert_out)

tf.Tensor([201 213 205 194 265 272 191  13], shape=(8,), dtype=int32)


In [75]:
print('vert_lines',vert_lines),print('horiz_lines',horiz_lines)

vert_lines [ 13 191 194 201 205 213 265 272]
horiz_lines [  0   1   2   3   4   6   8  10  11  13  15  20  23  29  31  42  44  52
  60  70  76  83  94  99 106 112 122 127 137 144 153 158 170 174 176 186
 194 201 205 213 220 232 238 242 247 258 265 272 281]


(None, None)

### Convert to csv

In [76]:
out_array=[["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(out_array)

[['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', 

In [77]:
print(np.array(out_array).shape)

(49, 8)


In [78]:
unordered_boxes=[]

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[465, 0, 726, 2338]
[866, 0, 940, 2338]
[986, 0, 1006, 2338]
[1242, 0, 1328, 2338]
[797, 0, 841, 2338]
[1082, 0, 1168, 2338]
[723, 0, 750, 2338]
[371, 0, 398, 2338]


In [79]:
ordered_boxes=np.argsort(unordered_boxes)
print(ordered_boxes)

[7 0 6 4 1 2 5 3]


In [80]:
def intersection(box1,box2):
  return [box2[0],box1[1],box2[2],box1[3]]

In [81]:
def iou(box1,box2):
  x1=max(box1[0],box2[0])
  y1=max(box1[1],box2[1])
  x2=min(box1[2],box2[2])
  y2=min(box1[3],box2[3])

  inter=abs(max((x2-x1,0))*max((y2-y1),0))
  if inter==0:
    return 0

  box1area=abs((box1[2]-box1[0])*(box1[3]-box1[1]))
  box2area=abs((box2[2]-box2[0])*(box2[3]-box2[1]))

  return inter/float(box1area+box2area-inter)

In [82]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant=intersection(horiz_boxes[horiz_lines[i]],vert_boxes[vert_lines[ordered_boxes[j]]])
    
    for b in range(len(boxes)):
      the_box=[boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if (iou(resultant,the_box)>0.1):
        out_array[i][j]=texts[b]
        # print(out_array)
    # print(resultant)

In [83]:
out_array

[['', 'KA', '', '', 'KA', '', 'KA', ''],
 ['',
  'Xiamen Changsu Industrial Corporation Limited',
  '',
  '',
  'Xiamen Changsu Industrial Corporation Limited',
  '',
  'Xiamen Changsu Industrial Corporation Limited',
  ''],
 ['',
  'ADD:No. 268 Wengjiao Road. Xinyang Industrial Zone, Haicang Xiamen. 361026 China',
  '',
  '',
  '',
  '',
  'ADD:No. 268 Wengjiao Road. Xinyang Industrial Zone, Haicang Xiamen. 361026 China',
  ''],
 ['',
  'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
  '',
  '',
  'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
  '',
  'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
  ''],
 ['', '', '', 'PACKING LIST', 'PACKING LIST', '', '', ''],
 ['',
  'Messrs:Mag Data-S.p.A',
  '',
  '',
  'Invoice No.: CS210746',
  '',
  'Invoice No.: CS210746',
  ''],
 ['',
  '43052 Colorno (Italy)',
  '',
  '',
  'Date: September 14, 2021',
  '',
  'Date: September 14, 2021',
  ''],
 ['', '43052 Colorno (Italy)', '', '', 

In [84]:
# horiz_boxes

In [85]:
texts

['KA',
 'Xiamen Changsu Industrial Corporation Limited',
 'ADD:No. 268 Wengjiao Road. Xinyang Industrial Zone, Haicang Xiamen. 361026 China',
 'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
 'PACKING LIST',
 'Messrs:Mag Data-S.p.A',
 'Invoice No.: CS210746',
 'Strada della Selva 100/2',
 'Date: September 14, 2021',
 '43052 Colorno (Italy)',
 'Payment: TT',
 'Tel. 0039-0521-525320',
 'Incoterms: CIF La Spezia, Italy',
 'Fax. 0039-0521-525329',
 'PO No.:1266',
 'FROM:XIAMEN,CHINA',
 'TO:LA SPEZIA,ITALY',
 'Specification',
 "Qt'y",
 ' Net Weight',
 'Gross Weight',
 'Type of',
 'Item',
 'Commodity',
 ' Material',
 'T(m)[W(mm)',
 'L(m)',
 'Roll',
 'kg',
 'kg',
 '20',
 '860',
 '15000',
 '4',
 '1195.70',
 '1',
 '1315.27',
 '2',
 '20',
 '900',
 '15000',
 '2',
 '624.80',
 '687.28',
 '20',
 '1240',
 '15000',
 '3',
 '2',
 '850.80',
 '935.88',
 '1048.30',
 '24000',
 '15',
 '4',
 '630',
 '4',
 '1153.13',
 '650',
 '5',
 '15',
 '24000',
 '2',
 '533.80',
 '587.18',
 'OA1',
 '24000'

In [86]:
out_array

[['', 'KA', '', '', 'KA', '', 'KA', ''],
 ['',
  'Xiamen Changsu Industrial Corporation Limited',
  '',
  '',
  'Xiamen Changsu Industrial Corporation Limited',
  '',
  'Xiamen Changsu Industrial Corporation Limited',
  ''],
 ['',
  'ADD:No. 268 Wengjiao Road. Xinyang Industrial Zone, Haicang Xiamen. 361026 China',
  '',
  '',
  '',
  '',
  'ADD:No. 268 Wengjiao Road. Xinyang Industrial Zone, Haicang Xiamen. 361026 China',
  ''],
 ['',
  'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
  '',
  '',
  'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
  '',
  'Tel:+86-592-6800888 Fax:86-592-6806585 http/www.chang-su.com.cn',
  ''],
 ['', '', '', 'PACKING LIST', 'PACKING LIST', '', '', ''],
 ['',
  'Messrs:Mag Data-S.p.A',
  '',
  '',
  'Invoice No.: CS210746',
  '',
  'Invoice No.: CS210746',
  ''],
 ['',
  '43052 Colorno (Italy)',
  '',
  '',
  'Date: September 14, 2021',
  '',
  'Date: September 14, 2021',
  ''],
 ['', '43052 Colorno (Italy)', '', '', 

In [87]:
import pandas as pd
pd.DataFrame(out_array).to_csv('sample.csv')

In [88]:
df=pd.DataFrame(out_array)
df

0                                                  1  \
0                                                        KA   
1             Xiamen Changsu Industrial Corporation Limited   
2         ADD:No. 268 Wengjiao Road. Xinyang Industrial ...   
3         Tel:+86-592-6800888 Fax:86-592-6806585 http/ww...   
4                                                             
5                                     Messrs:Mag Data-S.p.A   
6                                     43052 Colorno (Italy)   
7                                     43052 Colorno (Italy)   
8                                     Tel. 0039-0521-525320   
9                                     Fax. 0039-0521-525329   
10                                        FROM:XIAMEN,CHINA   
11                                                  Type of   
12  Item                                           Material   
13                                                 Material   
14     1                                                      
15     2                                                      
16     3                                                      
17     4                                                      
18     5                                                      
19     6                                                OA1   
20     7                                           treated)   
21     8                                                      
22     9                                                      
23    10                                           BOPAFILM   
24    11                                                      
25    12                                                      
26    13                                                      
27    14                                                      
28    15                                                OA2   
29    16                                              sides   
30    17                                           treated)   
31    18                                                      
32    19                                                      
33                         Sub-total (CMAU9079588/C1856699)   
34     1                                                      
35     2                                                      
36     3                                                      
37                                                            
38     5                                                      
39     6                                           (Outside   
40     7                                           treated)   
41     8                                          BOPA FILM   
42     9                                                      
43    10                                                      
44    11                                                      
45    12                                                      
46    13                                               Both   
47    14                                           treated)   
48                         Sub-total (CMAU8246588/C0822401)   

                    2                  3  \
0                                          
1                                          
2                                          
3                                          
4                           PACKING LIST   
5                                          
6                                          
7                                          
8                                          
9                                          
10  FROM:XIAMEN,CHINA  FROM:XIAMEN,CHINA   
11                         Specification   
12                                         
13         T(m)[W(mm)         T(m)[W(mm)   
14                 20                860   
15                 20                900   
16                 20               1240   
17                 15                630   
18                 1