In [161]:
!pip3 install paddlepaddle -i https://mirror.baidu.com/pypi/simple/

Looking in indexes: https://mirror.baidu.com/pypi/simple/, https://us-python.pkg.dev/colab-wheels/public/simple/


In [162]:
# git clone https://github.com/PaddlePaddle/PaddleOCR.git

In [163]:
!pip install paddlepaddle-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [164]:
!pip install paddleocr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [165]:
# Importing required functions for inference and visualization.
from paddleocr import PaddleOCR,draw_ocr 
import os
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
# ocr = PaddleOCR(use_angle_cls=True)

In [166]:
# from paddleocr import PaddleOCR,draw_ocr
# # Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# # You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# # to switch the language model in order.
# ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
# img_path = '/content/English_text.webp'
# result = ocr.ocr(img_path, cls=True)
# for line in result:
#      print(line)
# # draw result
# from PIL import Image
# image = Image.open(img_path).convert('RGB')
# boxes = [line[0] for line in result]
# txts = [line[1][0] for line in result]
# scores = [line[1][1] for line in result]
# im_show = draw_ocr(image, boxes, txts, scores, font_path='/content/PaddleOCR/doc/fonts/simfang.ttf')
# im_show = Image.fromarray(im_show)
# im_show.save('result.jpg')

In [167]:
from paddleocr import PaddleOCR,draw_ocr
ocr=PaddleOCR(lang="en")

[2022/08/09 19:28:41] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='f

In [168]:
image_path='/content/BRIC_S FATT + PL (SI21307931 CHENNAI)page-10.jpg'
image_cv=cv2.imread(image_path)
image_height=image_cv.shape[0]
image_width=image_cv.shape[1]
output=ocr.ocr(image_path)

[2022/08/09 19:28:42] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/08/09 19:28:42] ppocr DEBUG: dt_boxes num : 296, elapse : 0.23663616180419922
[2022/08/09 19:28:43] ppocr DEBUG: rec_res num  : 296, elapse : 0.5241961479187012


In [169]:
print(output)

[[[[1316.0, 75.0], [1341.0, 75.0], [1341.0, 100.0], [1316.0, 100.0]], ('IT', 0.9260329008102417)], [[[368.0, 78.0], [724.0, 78.0], [724.0, 109.0], [368.0, 109.0]], (' Ponza Mezza|una LUNA 006-Blu 35x21x11', 0.976459801197052)], [[[1071.0, 78.0], [1186.0, 78.0], [1186.0, 102.0], [1071.0, 102.0]], ('1 PVC/PU/PL', 0.9999372959136963)], [[[194.0, 80.0], [322.0, 80.0], [322.0, 107.0], [194.0, 107.0]], ('BOZ05800.006', 0.982062816619873)], [[[813.0, 80.0], [955.0, 80.0], [955.0, 104.0], [813.0, 104.0]], ('8016623881362', 0.9999877214431763)], [[[1461.0, 73.0], [1552.0, 73.0], [1552.0, 100.0], [1461.0, 100.0]], ('42022210', 0.9999792575836182)], [[[133.0, 83.0], [157.0, 83.0], [157.0, 104.0], [133.0, 104.0]], ('16', 0.9993696212768555)], [[[1314.0, 100.0], [1346.0, 100.0], [1346.0, 131.0], [1314.0, 131.0]], ('IT', 0.8587839603424072)], [[[1071.0, 102.0], [1186.0, 102.0], [1186.0, 129.0], [1071.0, 129.0]], ('3 PVC/PU/PL', 0.9561151266098022)], [[[813.0, 104.0], [955.0, 104.0], [955.0, 131.0], 

In [170]:
boxes=[line[0] for line in output]
texts=[line[1][0] for line in output]
probabilities=[line[1][1] for line in output]

In [171]:
image_boxes=image_cv.copy()

In [172]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes,(int(box[0][0]),int(box[0][1])),(int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes,text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [173]:
cv2.imwrite('detections.jpg',image_boxes)

True

### Reconstruction 

In [174]:
im=image_cv.copy()

In [175]:
horiz_boxes=[]
vert_boxes=[]

for box in boxes:
  x_h,x_v=0,int(box[0][0])
  y_h,y_v=int(box[0][1]),0
  width_h,width_v=image_width,int(box[2][0]-box[0][0])
  height_h,height_v=int(box[2][1]-box[0][1]),image_height
                                    
  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h),(x_h+width_h,y_h+height_h),(255,255,0),1)
  cv2.rectangle(im,(x_v,y_v),(x_v+width_v,y_v+height_v),(255,255,0),1)

In [176]:
boxes[0]

[[1316.0, 75.0], [1341.0, 75.0], [1341.0, 100.0], [1316.0, 100.0]]

In [177]:
horiz_boxes[0]

[0, 75, 1650, 100]

In [178]:
cv2.imwrite('horiz_vert.jpg',im)

True

In [179]:
# cv2.imwrite('vert.jpg',im)

In [180]:
import tensorflow as tf
horiz_out=tf.image.non_max_suppression(horiz_boxes,
                                       probabilities,
                                       max_output_size=1000,
                                       iou_threshold=0.1,
                                       score_threshold=float('-inf'),
                                       name=None)

In [181]:
print(horiz_out)

tf.Tensor(
[245  94 256  71 221  80  41 144  58 289 176 134 206  49  69 184 240   4
 276 155 228  17 115 123   9 110 190  34 131 280 104 265  90 165 148 214
 233  45 172 260  25 293 199], shape=(43,), dtype=int32)


In [182]:
import numpy as np
horiz_lines=np.sort(np.array(horiz_out))
print(horiz_lines)

[  4   9  17  25  34  41  45  49  58  69  71  80  90  94 104 110 115 123
 131 134 144 148 155 165 172 176 184 190 199 206 214 221 228 233 240 245
 256 260 265 276 280 289 293]


In [183]:
in_nms=image_cv.copy()

In [184]:
for val in horiz_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(horiz_boxes[val][0]),int(horiz_boxes[val][1])),(int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [185]:
cv2.imwrite('im_nms.jpg',in_nms)

True

In [186]:
vert_out=tf.image.non_max_suppression(vert_boxes,
                                      probabilities,
                                      max_output_size=1000,
                                      iou_threshold=0.1,
                                      score_threshold=float('-inf'),
                                      name=None)

In [187]:
vert_lines=np.sort(np.array(vert_out))
print(vert_lines)

[ 46  75  94 133 182 245 256]


In [188]:
for val in vert_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(vert_boxes[val][0]),int(vert_boxes[val][1])),(int(vert_boxes[val][2]),int(vert_boxes[val][3])),(0,0,255),1)

In [189]:
cv2.imwrite('im_nms1.jpg',in_nms)

True

In [190]:
print(vert_out)

tf.Tensor([245  94 256 133  46  75 182], shape=(7,), dtype=int32)


In [191]:
print('vert_lines',vert_lines),print('horiz_lines',horiz_lines)

vert_lines [ 46  75  94 133 182 245 256]
horiz_lines [  4   9  17  25  34  41  45  49  58  69  71  80  90  94 104 110 115 123
 131 134 144 148 155 165 172 176 184 190 199 206 214 221 228 233 240 245
 256 260 265 276 280 289 293]


(None, None)

### Convert to csv

In [192]:
out_array=[["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(out_array)

[['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', 

In [193]:
print(np.array(out_array).shape)

(43, 7)


In [194]:
unordered_boxes=[]

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[1071, 0, 1186, 2330]
[371, 0, 604, 2330]
[813, 0, 955, 2330]
[192, 0, 322, 2330]
[1314, 0, 1350, 2330]
[128, 0, 155, 2330]
[1458, 0, 1552, 2330]


In [195]:
ordered_boxes=np.argsort(unordered_boxes)
print(ordered_boxes)

[5 3 1 2 0 4 6]


In [196]:
def intersection(box1,box2):
  return [box2[0],box1[1],box2[2],box1[3]]

In [197]:
def iou(box1,box2):
  x1=max(box1[0],box2[0])
  y1=max(box1[1],box2[1])
  x2=min(box1[2],box2[2])
  y2=min(box1[3],box2[3])

  inter=abs(max((x2-x1,0))*max((y2-y1),0))
  if inter==0:
    return 0

  box1area=abs((box1[2]-box1[0])*(box1[3]-box1[1]))
  box2area=abs((box2[2]-box2[0])*(box2[3]-box2[1]))

  return inter/float(box1area+box2area-inter)

In [198]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant=intersection(horiz_boxes[horiz_lines[i]],vert_boxes[vert_lines[ordered_boxes[j]]])
    
    for b in range(len(boxes)):
      the_box=[boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if (iou(resultant,the_box)>0.1):
        out_array[i][j]=texts[b]
        # print(out_array)
    # print(resultant)

In [199]:
out_array

[['16',
  'BOZ05800.006',
  ' Ponza Mezza|una LUNA 006-Blu 35x21x11',
  '8016623881362',
  '1 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05802.006',
  'Ponza Shoulderbag S MARTINA 006 Blue',
  '8016623710563',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05803.001',
  'Ponza Shopping LUDOVICA 001 Black',
  '8016623881690',
  '1 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05803.025',
  'Ponza Shopping LUDOVICA 025-Beige',
  '8016623882796',
  '1 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05805.001',
  'Ponza Shoulderbag EMMA 001 Black',
  '8016623725574',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05805.006',
  'Ponza Shoulderbag EMMA 006 Blue',
  '8016623725581',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ0S805.020',
  'Ponza Shoulderbag EMMA 020-Bordeaux',
  '8016623725598',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BPL05802.098',
  ' Life Pelle Shoul.bag S MARTINA 098 Leather',
  '8016623605920',
  '1 Leather',
  'IT',
  '42022

In [200]:
# horiz_boxes

In [201]:
texts

['IT',
 ' Ponza Mezza|una LUNA 006-Blu 35x21x11',
 '1 PVC/PU/PL',
 'BOZ05800.006',
 '8016623881362',
 '42022210',
 '16',
 'IT',
 '3 PVC/PU/PL',
 '8016623710563',
 '16',
 'BOZ05802.006',
 'Ponza Shoulderbag S MARTINA 006 Blue',
 '42022210',
 'BOZ05803.001',
 'Ponza Shopping LUDOVICA 001 Black',
 'IT',
 '8016623881690',
 '1 PVC/PU/PL',
 '16',
 '42022210',
 'IT',
 'BOZ05803.025',
 'Ponza Shopping LUDOVICA 025-Beige',
 '8016623882796',
 '1 PVC/PU/PL',
 '16',
 '42022210',
 'IT',
 'Ponza Shoulderbag EMMA 001 Black',
 '8016623725574',
 '3 PVC/PU/PL',
 'BOZ05805.001',
 '16',
 '42022210',
 'Ponza Shoulderbag EMMA 006 Blue',
 'BOZ05805.006',
 '8016623725581',
 '3 PVC/PU/PL',
 'IT',
 '16',
 '42022210',
 'Ponza Shoulderbag EMMA 020-Bordeaux',
 'IT',
 'BOZ0S805.020',
 '8016623725598',
 '3 PVC/PU/PL',
 '16',
 '42022210',
 '8016623605920',
 '1 Leather',
 'IT',
 '16',
 'BPL05802.098',
 ' Life Pelle Shoul.bag S MARTINA 098 Leather',
 '4202210090',
 'X-Bag Shoulderbag 207-Mocca',
 'BXG45051.207',
 '8016

In [202]:
out_array

[['16',
  'BOZ05800.006',
  ' Ponza Mezza|una LUNA 006-Blu 35x21x11',
  '8016623881362',
  '1 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05802.006',
  'Ponza Shoulderbag S MARTINA 006 Blue',
  '8016623710563',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05803.001',
  'Ponza Shopping LUDOVICA 001 Black',
  '8016623881690',
  '1 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05803.025',
  'Ponza Shopping LUDOVICA 025-Beige',
  '8016623882796',
  '1 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05805.001',
  'Ponza Shoulderbag EMMA 001 Black',
  '8016623725574',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ05805.006',
  'Ponza Shoulderbag EMMA 006 Blue',
  '8016623725581',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BOZ0S805.020',
  'Ponza Shoulderbag EMMA 020-Bordeaux',
  '8016623725598',
  '3 PVC/PU/PL',
  'IT',
  '42022210'],
 ['16',
  'BPL05802.098',
  ' Life Pelle Shoul.bag S MARTINA 098 Leather',
  '8016623605920',
  '1 Leather',
  'IT',
  '42022

In [203]:
import pandas as pd
pd.DataFrame(out_array).to_csv('sample.csv')

In [204]:
df=pd.DataFrame(out_array)
df

0              1                                            2  \
0   16   BOZ05800.006        Ponza Mezza|una LUNA 006-Blu 35x21x11   
1   16   BOZ05802.006         Ponza Shoulderbag S MARTINA 006 Blue   
2   16   BOZ05803.001            Ponza Shopping LUDOVICA 001 Black   
3   16   BOZ05803.025            Ponza Shopping LUDOVICA 025-Beige   
4   16   BOZ05805.001             Ponza Shoulderbag EMMA 001 Black   
5   16   BOZ05805.006              Ponza Shoulderbag EMMA 006 Blue   
6   16   BOZ0S805.020          Ponza Shoulderbag EMMA 020-Bordeaux   
7   16   BPL05802.098   Life Pelle Shoul.bag S MARTINA 098 Leather   
8   17   BXG45051.207                  X-Bag Shoulderbag 207-Mocca   
9   17   BXG45057.207                  X-Bag Shoulderbag 207-Mocca   
10  17   BXG45070.207                     X-Bag Shopping 207-Mocca   
11  17   BXG45070.412                      X-Bag Shopping 412-Rock   
12  17   BXG45071.207              X-Bag Medium Sportina 207-Mocca   
13  17   BXG45072.412                X-Bag Small Sportina 412-Rock   
14  17  BXl.43754.207     X-Travel City Backpack Piccolo 207-Mocca   
15  18   BXG40606.207             X-Bag Urban Travel Kit 207-Mocca   
16  18   BXG40606.412              X-Bag Urban Travel Kit 412-Rock   
17  18   BXG45052.207                  X-Bag Shoulderbag 207-Mocca   
18       BXG45052.412                   X-Bag Shoulderbag 412-Rock   
19  18   BXG45056.207                  X-Bag Shou!derbag 207-Mocca   
20       BXG45056.412                   X-Bag Shoulderbag 412-Rock   
21  18   BXG45072.207               X-Bag Small Sportina 207-Mocca   
22  19   BXG45057.412                   X-Bag Shoulderbag 412-Rock   
23  19   BXG45282.207                      X-Bag Handbag 207-Mocca   
24  19   BXL43754.412      X-Travel City Backpack Piccoto 412-Rock   
25  19   8XL45059.412                   X-Travel Backpack 412-Rock   
26  20   BXG45071.207              X-Bag Medium Sportina 207-Mocca   
27  29   BXL40202.207                   X-Travel Ho!dall 207-Mocca   
28  2(  6X1.42192.207                   X-Travel Ho!dall 207-Mocca   
29  20  BXI.42192.412                    X-Travel Ho!dall 412-Rock   
30  20  BXi.45059.207                   X-8ag Shoulderbag 412-Rock   
31  21   BXG45051.412                   X-Bag Shoulderbag 412-Rock   
32  21   BXG45055.412                   X-Bag Shoulderbag 412-Rock   
33  21   BXG45071.412               X-Bag Medium Sportina 412-Rock   
34  21   BXG45282.412                       X-Bag Handbag 412-Rock   
35  21   BXL45059.207                  X-Travel Backpack 207-Mocca   
36  22   BXL40202.412                  X-8ag Shoulderbag 207-Mocca   
37  22   BXL40202.412                    X-Travel Holdatl 412-Rock   
38  23   BXG40202.207                      X-Bag Holdall 207-Mocca   
39  23   BXG40202.412                       X-Bag Holdall 412-Rock   
40  23   BXG40203.207                      X-Bag Hotdatl 207-Mocca   
41  23   BXG40203.412                       X-Bag Holdall 412-Rock   
42                                                                   

                3                     4   5           6  
0   8016623881362           1 PVC/PU/PL  IT    42022210  
1   8016623710563           3 PVC/PU/PL  IT    42022210  
2   8016623881690           1 PVC/PU/PL  IT    42022210  
3   8016623882796           1 PVC/PU/PL  IT    42022210  
4   8016623725574           3 PVC/PU/PL  IT    42022210  
5   8016623725581           3 PVC/PU/PL  IT    42022210  
6   8016623725598           3 PVC/PU/PL  IT    42022210  
7   8016623605920             1 Leather  IT  4202210090  
8   8016623609515   2 Polyamide/Leather  CN    42022290  
9   8016623616216   6 Polyamide/Leather  CN    42022290  
10  8016623123684   2 Polyamide/Leather  CN    42022290  
11  8016623616230   2 Polyamide/Leather  CN    42022290  
12  8016623115412   2 Polyamide/Leather  CN    42022290  
13  8016623616254   3 Polyamide/Leather  CN    42022290  
14  8016623115467   5 Polyamide/Leather  CN    4202229