In [115]:
!pip3 install paddlepaddle -i https://mirror.baidu.com/pypi/simple/

Looking in indexes: https://mirror.baidu.com/pypi/simple/, https://us-python.pkg.dev/colab-wheels/public/simple/


In [116]:
# git clone https://github.com/PaddlePaddle/PaddleOCR.git

In [117]:
!pip install paddlepaddle-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [118]:
!pip install paddleocr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [119]:
# Importing required functions for inference and visualization.
from paddleocr import PaddleOCR,draw_ocr 
import os
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
# ocr = PaddleOCR(use_angle_cls=True)

In [120]:
# from paddleocr import PaddleOCR,draw_ocr
# # Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# # You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# # to switch the language model in order.
# ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
# img_path = '/content/English_text.webp'
# result = ocr.ocr(img_path, cls=True)
# for line in result:
#      print(line)
# # draw result
# from PIL import Image
# image = Image.open(img_path).convert('RGB')
# boxes = [line[0] for line in result]
# txts = [line[1][0] for line in result]
# scores = [line[1][1] for line in result]
# im_show = draw_ocr(image, boxes, txts, scores, font_path='/content/PaddleOCR/doc/fonts/simfang.ttf')
# im_show = Image.fromarray(im_show)
# im_show.save('result.jpg')

In [121]:
from paddleocr import PaddleOCR,draw_ocr
ocr=PaddleOCR(lang="en")

[2022/08/09 19:22:17] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='f

In [122]:
image_path='/content/Table_1.jpeg'
image_cv=cv2.imread(image_path)
image_height=image_cv.shape[0]
image_width=image_cv.shape[1]
output=ocr.ocr(image_path)

[2022/08/09 19:22:17] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/08/09 19:22:18] ppocr DEBUG: dt_boxes num : 379, elapse : 0.17516732215881348
[2022/08/09 19:22:18] ppocr DEBUG: rec_res num  : 379, elapse : 0.6517455577850342


In [123]:
print(output)

[[[[18.0, 15.0], [164.0, 25.0], [160.0, 80.0], [14.0, 70.0]], ('Bill To:', 0.9824225902557373)], [[[1843.0, 24.0], [2044.0, 24.0], [2044.0, 51.0], [1843.0, 51.0]], ('TIOUEDt', 0.50394606590271)], [[[1352.0, 263.0], [1468.0, 263.0], [1468.0, 303.0], [1352.0, 303.0]], ('INDIA', 0.9994415044784546)], [[[1356.0, 326.0], [2090.0, 326.0], [2090.0, 365.0], [1356.0, 365.0]], ('S-027,GROUND FLOOR,EXPRESS Av.MALL', 0.9894180297851562)], [[[1358.0, 455.0], [1543.0, 464.0], [1540.0, 520.0], [1355.0, 510.0]], ('Your Ref.', 0.9961475729942322)], [[[19.0, 468.0], [386.0, 463.0], [387.0, 507.0], [20.0, 511.0]], ('Fustomer Order N#', 0.9615918397903442)], [[[437.0, 468.0], [533.0, 468.0], [533.0, 511.0], [437.0, 511.0]], ('Date', 0.9988164901733398)], [[[746.0, 468.0], [947.0, 468.0], [947.0, 511.0], [746.0, 511.0]], ('Your Order', 0.9870894551277161)], [[[212.0, 515.0], [355.0, 515.0], [355.0, 558.0], [212.0, 558.0]], ('4108361', 0.9957239031791687)], [[[23.0, 519.0], [100.0, 519.0], [100.0, 562.0], [

In [124]:
boxes=[line[0] for line in output]
texts=[line[1][0] for line in output]
probabilities=[line[1][1] for line in output]

In [125]:
image_boxes=image_cv.copy()

In [126]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes,(int(box[0][0]),int(box[0][1])),(int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes,text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [127]:
cv2.imwrite('detections.jpg',image_boxes)

True

### Reconstruction 

In [128]:
im=image_cv.copy()

In [129]:
horiz_boxes=[]
vert_boxes=[]

for box in boxes:
  x_h,x_v=0,int(box[0][0])
  y_h,y_v=int(box[0][1]),0
  width_h,width_v=image_width,int(box[2][0]-box[0][0])
  height_h,height_v=int(box[2][1]-box[0][1]),image_height
                                    
  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h),(x_h+width_h,y_h+height_h),(255,255,0),1)
  cv2.rectangle(im,(x_v,y_v),(x_v+width_v,y_v+height_v),(255,255,0),1)

In [130]:
boxes[0]

[[18.0, 15.0], [164.0, 25.0], [160.0, 80.0], [14.0, 70.0]]

In [131]:
horiz_boxes[0]

[0, 15, 2720, 80]

In [132]:
cv2.imwrite('horiz_vert.jpg',im)

True

In [133]:
# cv2.imwrite('vert.jpg',im)

In [134]:
import tensorflow as tf
horiz_out=tf.image.non_max_suppression(horiz_boxes,
                                       probabilities,
                                       max_output_size=1000,
                                       iou_threshold=0.1,
                                       score_threshold=float('-inf'),
                                       name=None)

In [135]:
print(horiz_out)

tf.Tensor(
[338 247 359 254 240 324 163 233 318 282 214 269 344 178 286 157 296 226
 188 304 171 145 195 276 206  10 111 135 352 376 198 151 332 312 121 369
 366 138  96  17 115 126   2 128  59  53  34  74  81  65  91   6  46  31
 218  83  25  68 100 261  39  48  19   3 105   0], shape=(66,), dtype=int32)


In [136]:
import numpy as np
horiz_lines=np.sort(np.array(horiz_out))
print(horiz_lines)

[  0   2   3   6  10  17  19  25  31  34  39  46  48  53  59  65  68  74
  81  83  91  96 100 105 111 115 121 126 128 135 138 145 151 157 163 171
 178 188 195 198 206 214 218 226 233 240 247 254 261 269 276 282 286 296
 304 312 318 324 332 338 344 352 359 366 369 376]


In [137]:
in_nms=image_cv.copy()

In [138]:
for val in horiz_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(horiz_boxes[val][0]),int(horiz_boxes[val][1])),(int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [139]:
cv2.imwrite('im_nms.jpg',in_nms)

True

In [140]:
vert_out=tf.image.non_max_suppression(vert_boxes,
                                      probabilities,
                                      max_output_size=1000,
                                      iou_threshold=0.1,
                                      score_threshold=float('-inf'),
                                      name=None)

In [141]:
vert_lines=np.sort(np.array(vert_out))
print(vert_lines)

[ 10  17 111 126 188 259 309 338 352]


In [142]:
for val in vert_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(vert_boxes[val][0]),int(vert_boxes[val][1])),(int(vert_boxes[val][2]),int(vert_boxes[val][3])),(0,0,255),1)

In [143]:
cv2.imwrite('im_nms1.jpg',in_nms)

True

In [144]:
print(vert_out)

tf.Tensor([338 188  10 111 259 352  17 126 309], shape=(9,), dtype=int32)


In [145]:
print('vert_lines',vert_lines),print('horiz_lines',horiz_lines)

vert_lines [ 10  17 111 126 188 259 309 338 352]
horiz_lines [  0   2   3   6  10  17  19  25  31  34  39  46  48  53  59  65  68  74
  81  83  91  96 100 105 111 115 121 126 128 135 138 145 151 157 163 171
 178 188 195 198 206 214 218 226 233 240 247 254 261 269 276 282 286 296
 304 312 318 324 332 338 344 352 359 366 369 376]


(None, None)

### Convert to csv

In [146]:
out_array=[["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(out_array)

[['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', ''

In [147]:
print(np.array(out_array).shape)

(66, 9)


In [148]:
unordered_boxes=[]

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[440, 0, 587, 3772]
[2102, 0, 2334, 3772]
[1198, 0, 1294, 3772]
[135, 0, 259, 3772]
[2569, 0, 2716, 3772]
[73, 0, 124, 3772]
[522, 0, 1275, 3772]
[1352, 0, 1611, 3772]
[1835, 0, 2044, 3772]


In [149]:
ordered_boxes=np.argsort(unordered_boxes)
print(ordered_boxes)

[5 3 0 6 2 7 8 1 4]


In [150]:
def intersection(box1,box2):
  return [box2[0],box1[1],box2[2],box1[3]]

In [151]:
def iou(box1,box2):
  x1=max(box1[0],box2[0])
  y1=max(box1[1],box2[1])
  x2=min(box1[2],box2[2])
  y2=min(box1[3],box2[3])

  inter=abs(max((x2-x1,0))*max((y2-y1),0))
  if inter==0:
    return 0

  box1area=abs((box1[2]-box1[0])*(box1[3]-box1[1]))
  box2area=abs((box2[2]-box2[0])*(box2[3]-box2[1]))

  return inter/float(box1area+box2area-inter)

In [152]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant=intersection(horiz_boxes[horiz_lines[i]],vert_boxes[vert_lines[ordered_boxes[j]]])
    
    for b in range(len(boxes)):
      the_box=[boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if (iou(resultant,the_box)>0.1):
        out_array[i][j]=texts[b]
        # print(out_array)
    # print(resultant)

In [153]:
out_array

[['Bill To:', 'Bill To:', '', '', '', '', 'TIOUEDt', '', ''],
 ['', '', '', '', '', 'INDIA', '', '', ''],
 ['',
  '',
  '',
  '',
  '',
  'S-027,GROUND FLOOR,EXPRESS Av.MALL',
  'S-027,GROUND FLOOR,EXPRESS Av.MALL',
  '',
  ''],
 ['Fustomer Order N#',
  'Fustomer Order N#',
  'Date',
  'Your Order',
  '',
  'Your Ref.',
  '',
  '',
  ''],
 ['913', '4108361', '4/6/2021', '', '', 'MR. DOSHI', '', '', ''],
 ['Pckg N# Pckg Type',
  'Pckg N# Pckg Type',
  'Pckg Size(Mt)',
  'Pckg Size(Mt)',
  'Gross Weight (Kg)',
  'Net Weight (Kg)',
  'Volume (Mc)',
  'Tracking Nbr',
  ''],
 ['',
  '1 CRT',
  '0.42 x 0.42 x 0.67',
  '0.42 x 0.42 x 0.67',
  '6,56',
  '5,32',
  '0,09',
  '',
  ''],
 ['',
  '2 CRT',
  '0.42 x 0.42 x 0.67',
  '0.42 x 0.42 x 0.67',
  '6,56',
  '5,32',
  '0,09',
  '',
  ''],
 ['',
  '3 CRT',
  '0.08 x 0.08  0.63',
  '0.08 x 0.08  0.63',
  '1,40',
  '1,00',
  '0,023',
  '',
  ''],
 ['',
  '4 CRT',
  '0.38 x 0.38 x 0.6',
  '0.38 x 0.38 x 0.6',
  '3,97',
  '3,07',
  '0,062',
  '',


In [154]:
# horiz_boxes

In [155]:
texts

['Bill To:',
 'TIOUEDt',
 'INDIA',
 'S-027,GROUND FLOOR,EXPRESS Av.MALL',
 'Your Ref.',
 'Fustomer Order N#',
 'Date',
 'Your Order',
 '4108361',
 '913',
 '4/6/2021',
 'MR. DOSHI',
 'Pckg N# Pckg Type',
 'Gross Weight (Kg)',
 'Pckg Size(Mt)',
 'Net Weight (Kg)',
 'Volume (Mc)',
 'Tracking Nbr',
 '1 CRT',
 '6,56',
 '5,32',
 '0.42 x 0.42 x 0.67',
 '0,09',
 '5,32',
 '2 CRT',
 '6,56',
 '0,09',
 '0.42 x 0.42 x 0.67',
 '3 CRT',
 '0.08 x 0.08  0.63',
 '1,40',
 '1,00',
 '0,023',
 '4 CRT',
 '3,97',
 '3,07',
 '0.38 x 0.38 x 0.6',
 '0,062',
 '5 CRT',
 '3,07',
 '0.38 x 0.38 x 0.6',
 '3,97',
 '0,062',
 '6 CRT',
 '0.38 x 0.38 x 0.6',
 '3,97',
 '3,07',
 '0,062',
 '7 CRT',
 '5,32',
 '0,09',
 '0.42 x 0.42 x 0.67',
 '6,56',
 '8 CRT',
 '6,56',
 '0.42 x 0.42 x 0.67',
 '5,32',
 '0,09',
 '9 CRT',
 '2,50',
 '0,062',
 '0.38 x 0.38 x 0.6',
 '3,40',
 '10 CRT',
 '3,40',
 '2,50',
 '0.38 x 0.38 x 0.6',
 '0,062',
 '2,50',
 '11 CRT',
 '0.38 x 0.38 x 0.6',
 '3,40',
 '0,062',
 '12 CRT',
 '2,50',
 '0.38 x 0.38 x 0.6',


In [156]:
out_array

[['Bill To:', 'Bill To:', '', '', '', '', 'TIOUEDt', '', ''],
 ['', '', '', '', '', 'INDIA', '', '', ''],
 ['',
  '',
  '',
  '',
  '',
  'S-027,GROUND FLOOR,EXPRESS Av.MALL',
  'S-027,GROUND FLOOR,EXPRESS Av.MALL',
  '',
  ''],
 ['Fustomer Order N#',
  'Fustomer Order N#',
  'Date',
  'Your Order',
  '',
  'Your Ref.',
  '',
  '',
  ''],
 ['913', '4108361', '4/6/2021', '', '', 'MR. DOSHI', '', '', ''],
 ['Pckg N# Pckg Type',
  'Pckg N# Pckg Type',
  'Pckg Size(Mt)',
  'Pckg Size(Mt)',
  'Gross Weight (Kg)',
  'Net Weight (Kg)',
  'Volume (Mc)',
  'Tracking Nbr',
  ''],
 ['',
  '1 CRT',
  '0.42 x 0.42 x 0.67',
  '0.42 x 0.42 x 0.67',
  '6,56',
  '5,32',
  '0,09',
  '',
  ''],
 ['',
  '2 CRT',
  '0.42 x 0.42 x 0.67',
  '0.42 x 0.42 x 0.67',
  '6,56',
  '5,32',
  '0,09',
  '',
  ''],
 ['',
  '3 CRT',
  '0.08 x 0.08  0.63',
  '0.08 x 0.08  0.63',
  '1,40',
  '1,00',
  '0,023',
  '',
  ''],
 ['',
  '4 CRT',
  '0.38 x 0.38 x 0.6',
  '0.38 x 0.38 x 0.6',
  '3,97',
  '3,07',
  '0,062',
  '',


In [158]:
import pandas as pd
pd.DataFrame(out_array).to_csv('sample.csv')