In [1]:
!pip3 install paddlepaddle -i https://mirror.baidu.com/pypi/simple/

Looking in indexes: https://mirror.baidu.com/pypi/simple/, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 112.4 MB 61 kB/s 
     |████████████████████████████████| 394 kB 27.9 MB/s 


In [2]:
# git clone https://github.com/PaddlePaddle/PaddleOCR.git

In [3]:
!pip install paddlepaddle-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 393.8 MB 27 kB/s 


In [4]:
!pip install paddleocr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 334 kB 6.8 MB/s 
     |████████████████████████████████| 55.7 MB 1.2 MB/s 
     |████████████████████████████████| 604 kB 44.2 MB/s 
     |████████████████████████████████| 50 kB 7.6 MB/s 
     |████████████████████████████████| 2.8 MB 18.2 MB/s 
     |████████████████████████████████| 399 kB 52.3 MB/s 
     |████████████████████████████████| 204 kB 54.0 MB/s 
     |████████████████████████████████| 2.3 MB 25.3 MB/s 
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp37-cp37m-linux_x86_64.whl size=149859 sha256=ad0bfcbbd7cf3123b61e50ff87269dada25d246d6f2330fa35d23ff198f15c73
  Stored in directory: /root/.cache/pip/wheels/05/5f/ca/7c4367734892581bb5ff896f15027a932c551080b2abd3e00d
Successfully built python-Levenshtein
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.6.0.6

In [5]:
# Importing required functions for inference and visualization.
from paddleocr import PaddleOCR,draw_ocr 
import os
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
# ocr = PaddleOCR(use_angle_cls=True)

/usr/local/lib/python3.7/dist-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if not isinstance(key, collections.Hashable):


In [6]:
# from paddleocr import PaddleOCR,draw_ocr
# # Paddleocr supports Chinese, English, French, German, Korean and Japanese.
# # You can set the parameter `lang` as `ch`, `en`, `french`, `german`, `korean`, `japan`
# # to switch the language model in order.
# ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
# img_path = '/content/English_text.webp'
# result = ocr.ocr(img_path, cls=True)
# for line in result:
#      print(line)
# # draw result
# from PIL import Image
# image = Image.open(img_path).convert('RGB')
# boxes = [line[0] for line in result]
# txts = [line[1][0] for line in result]
# scores = [line[1][1] for line in result]
# im_show = draw_ocr(image, boxes, txts, scores, font_path='/content/PaddleOCR/doc/fonts/simfang.ttf')
# im_show = Image.fromarray(im_show)
# im_show.save('result.jpg')

In [7]:
from paddleocr import PaddleOCR,draw_ocr
ocr=PaddleOCR(lang="en")

download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to /root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer/en_PP-OCRv3_det_infer.tar


100%|██████████| 3.86M/3.86M [00:09<00:00, 394kiB/s] 


download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar to /root/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer/en_PP-OCRv3_rec_infer.tar


100%|██████████| 9.96M/9.96M [00:16<00:00, 617kiB/s] 


download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar


100%|██████████| 1.45M/1.45M [00:08<00:00, 169kiB/s]

[2022/08/09 22:17:15] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='f

In [8]:
image_path='/content/2-4.png'
image_cv=cv2.imread(image_path)
image_height=image_cv.shape[0]
image_width=image_cv.shape[1]
output=ocr.ocr(image_path)

[2022/08/09 22:17:17] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/08/09 22:17:20] ppocr DEBUG: dt_boxes num : 247, elapse : 3.180206060409546
[2022/08/09 22:17:22] ppocr DEBUG: rec_res num  : 247, elapse : 2.226088523864746


In [9]:
print(output)

[[[[453.0, 107.0], [699.0, 110.0], [699.0, 136.0], [453.0, 134.0]], ('DESCRIPTION OF GOODS.', 0.9420276880264282)], [[[57.0, 141.0], [155.0, 141.0], [155.0, 165.0], [57.0, 165.0]], ('Pallet No.', 0.9566475749015808)], [[[199.0, 141.0], [254.0, 141.0], [254.0, 168.0], [199.0, 168.0]], ('Type', 0.996271014213562)], [[[345.0, 141.0], [455.0, 141.0], [455.0, 168.0], [345.0, 168.0]], ('Width (MM)', 0.9692723155021667)], [[[583.0, 144.0], [657.0, 144.0], [657.0, 170.0], [583.0, 170.0]], ('Roll No.', 0.9640026688575745)], [[[749.0, 141.0], [911.0, 144.0], [910.0, 170.0], [748.0, 168.0]], (' Pallet Dimension', 0.9755622744560242)], [[[933.0, 148.0], [1061.0, 148.0], [1061.0, 173.0], [933.0, 173.0]], ('Length(Mtr.)', 0.9062156081199646)], [[[1095.0, 151.0], [1152.0, 151.0], [1152.0, 178.0], [1095.0, 178.0]], ('Joint', 0.9983579516410828)], [[[1290.0, 151.0], [1388.0, 151.0], [1388.0, 178.0], [1290.0, 178.0]], ('Gross Wt.', 0.9592328667640686)], [[[1501.0, 153.0], [1575.0, 153.0], [1575.0, 180.0

In [10]:
boxes=[line[0] for line in output]
texts=[line[1][0] for line in output]
probabilities=[line[1][1] for line in output]

In [11]:
image_boxes=image_cv.copy()

In [12]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes,(int(box[0][0]),int(box[0][1])),(int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes,text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [13]:
cv2.imwrite('detections.jpg',image_boxes)

True

### Reconstruction 

In [14]:
im=image_cv.copy()

In [15]:
horiz_boxes=[]
vert_boxes=[]

for box in boxes:
  x_h,x_v=0,int(box[0][0])
  y_h,y_v=int(box[0][1]),0
  width_h,width_v=image_width,int(box[2][0]-box[0][0])
  height_h,height_v=int(box[2][1]-box[0][1]),image_height
                                    
  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h),(x_h+width_h,y_h+height_h),(255,255,0),1)
  cv2.rectangle(im,(x_v,y_v),(x_v+width_v,y_v+height_v),(255,255,0),1)

In [16]:
boxes[0]

[[453.0, 107.0], [699.0, 110.0], [699.0, 136.0], [453.0, 134.0]]

In [17]:
horiz_boxes[0]

[0, 107, 1654, 136]

In [18]:
cv2.imwrite('horiz_vert.jpg',im)

True

In [19]:
# cv2.imwrite('vert.jpg',im)

In [20]:
import tensorflow as tf
horiz_out=tf.image.non_max_suppression(horiz_boxes,
                                       probabilities,
                                       max_output_size=1000,
                                       iou_threshold=0.1,
                                       score_threshold=float('-inf'),
                                       name=None)

In [21]:
print(horiz_out)

tf.Tensor(
[ 33 105 213  39  21  52  57 112 138  91 120  11 127  68 199 175 235 226
  24 193  86 147 181 161  75 239   7 154 149 221  27  96  42  80 131 167
  44 203  98 114 219  77  60 206 169 187 245 243 222  61 241 240 115 185
   0], shape=(55,), dtype=int32)


In [22]:
import numpy as np
horiz_lines=np.sort(np.array(horiz_out))
print(horiz_lines)

[  0   7  11  21  24  27  33  39  42  44  52  57  60  61  68  75  77  80
  86  91  96  98 105 112 114 115 120 127 131 138 147 149 154 161 167 169
 175 181 185 187 193 199 203 206 213 219 221 222 226 235 239 240 241 243
 245]


In [23]:
in_nms=image_cv.copy()

In [24]:
for val in horiz_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(horiz_boxes[val][0]),int(horiz_boxes[val][1])),(int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [25]:
cv2.imwrite('im_nms.jpg',in_nms)

True

In [26]:
vert_out=tf.image.non_max_suppression(vert_boxes,
                                      probabilities,
                                      max_output_size=1000,
                                      iou_threshold=0.1,
                                      score_threshold=float('-inf'),
                                      name=None)

In [27]:
vert_lines=np.sort(np.array(vert_out))
print(vert_lines)

[  5   7  10  11  33  56 138 161 213]


In [28]:
for val in vert_lines:
  # print(val)
  cv2.rectangle(in_nms,(int(vert_boxes[val][0]),int(vert_boxes[val][1])),(int(vert_boxes[val][2]),int(vert_boxes[val][3])),(0,0,255),1)

In [29]:
cv2.imwrite('im_nms1.jpg',in_nms)

True

In [30]:
print(vert_out)

tf.Tensor([ 33 213  56 138  11 161  10   7   5], shape=(9,), dtype=int32)


In [31]:
print('vert_lines',vert_lines),print('horiz_lines',horiz_lines)

vert_lines [  5   7  10  11  33  56 138 161 213]
horiz_lines [  0   7  11  21  24  27  33  39  42  44  52  57  60  61  68  75  77  80
  86  91  96  98 105 112 114 115 120 127 131 138 147 149 154 161 167 169
 175 181 185 187 193 199 203 206 213 219 221 222 226 235 239 240 241 243
 245]


(None, None)

### Convert to csv

In [32]:
out_array=[["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(out_array)

[['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', ''

In [33]:
print(np.array(out_array).shape)

(55, 9)


In [34]:
unordered_boxes=[]

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[749, 0, 910, 2336]
[1095, 0, 1152, 2336]
[150, 0, 234, 2336]
[84, 0, 111, 2336]
[1322, 0, 1396, 2336]
[975, 0, 1034, 2336]
[537, 0, 679, 2336]
[374, 0, 416, 2336]
[1489, 0, 1560, 2336]


In [35]:
ordered_boxes=np.argsort(unordered_boxes)
print(ordered_boxes)

[3 2 7 6 0 5 1 4 8]


In [36]:
def intersection(box1,box2):
  return [box2[0],box1[1],box2[2],box1[3]]

In [37]:
def iou(box1,box2):
  x1=max(box1[0],box2[0])
  y1=max(box1[1],box2[1])
  x2=min(box1[2],box2[2])
  y2=min(box1[3],box2[3])

  inter=abs(max((x2-x1,0))*max((y2-y1),0))
  if inter==0:
    return 0

  box1area=abs((box1[2]-box1[0])*(box1[3]-box1[1]))
  box2area=abs((box2[2]-box2[0])*(box2[3]-box2[1]))

  return inter/float(box1area+box2area-inter)

In [38]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant=intersection(horiz_boxes[horiz_lines[i]],vert_boxes[vert_lines[ordered_boxes[j]]])
    
    for b in range(len(boxes)):
      the_box=[boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if (iou(resultant,the_box)>0.1):
        out_array[i][j]=texts[b]
        # print(out_array)
    # print(resultant)

In [39]:
out_array

[['', '', '', 'DESCRIPTION OF GOODS.', '', '', '', '', ''],
 ['Pallet No.',
  'SM100T',
  'Width (MM)',
  'Roll No.',
  ' Pallet Dimension',
  'Length(Mtr.)',
  'Joint',
  'Gross Wt.',
  'Net Wt.'],
 ['19',
  'SM100T',
  '720',
  'M10 21P3032935',
  '',
  '24000',
  '',
  '293.800',
  '289.700'],
 ['',
  'SM100T',
  '720',
  'F10 21P3032938',
  '',
  '24000',
  '',
  '293.200',
  '289.100'],
 ['', '', '', '', '', '', 'PALLET WT', '48.500', ''],
 ['20',
  'SM100T',
  '720',
  'M10 21P3031869',
  '',
  '24000',
  'Total:',
  '635.500',
  '578.800'],
 ['20',
  'SM100T',
  '720',
  'M10 21P3032926',
  '',
  '24000',
  '',
  '292.800',
  '288.700'],
 ['',
  'SM100T',
  '720',
  'M10 21P3032926',
  '',
  '24000',
  '',
  '293.600',
  '289.500'],
 ['', '', '', '', '', '', 'PALLET WT', '48.500', ''],
 ['21',
  'SM100T',
  '720',
  'M10 21P3031860',
  '',
  '',
  'Total:',
  '634.900',
  '578.200'],
 ['21',
  'SM100T',
  '720',
  'F1021P3032929',
  '',
  '24000',
  '',
  '294.200',
  '290.100']

In [40]:
# horiz_boxes

In [41]:
texts

['DESCRIPTION OF GOODS.',
 'Pallet No.',
 'Type',
 'Width (MM)',
 'Roll No.',
 ' Pallet Dimension',
 'Length(Mtr.)',
 'Joint',
 'Gross Wt.',
 'Net Wt.',
 'SM100T',
 '19',
 '720',
 'M10 21P3032935',
 '24000',
 '293.800',
 '289.700',
 'SM100T',
 '720',
 'F10 21P3032938',
 '24000',
 '293.200',
 '289.100',
 'PALLET WT',
 '48.500',
 'Total:',
 '635.500',
 '578.800',
 '20',
 'SM100T',
 '720',
 'M10 21P3031869',
 '24000',
 '292.800',
 '288.700',
 'SM100T',
 '720',
 'M10 21P3032926',
 '24000',
 '293.600',
 '289.500',
 'PALLET WT',
 '48.500',
 'Total:',
 '634.900',
 'SM100T',
 '578.200',
 '21',
 '720',
 'M10 21P3031860',
 '24000',
 '294.200',
 '290.100',
 'SM100T',
 '720',
 'F1021P3032929',
 '24000',
 '292.000',
 '287.900',
 'PALLETWT',
 '48.500',
 'Total:',
 '634.700',
 '578.000',
 'SM100T',
 '22',
 '720',
 'D10 21P3034656',
 '24000',
 '286.200',
 '282.100',
 'SM100T',
 '720',
 'D10 21P3034901',
 '24000',
 '293.400',
 '289.300',
 'PALLETWT',
 '48.500',
 'Total:',
 '628.100',
 '571.400',
 'SM10

In [42]:
out_array

[['', '', '', 'DESCRIPTION OF GOODS.', '', '', '', '', ''],
 ['Pallet No.',
  'SM100T',
  'Width (MM)',
  'Roll No.',
  ' Pallet Dimension',
  'Length(Mtr.)',
  'Joint',
  'Gross Wt.',
  'Net Wt.'],
 ['19',
  'SM100T',
  '720',
  'M10 21P3032935',
  '',
  '24000',
  '',
  '293.800',
  '289.700'],
 ['',
  'SM100T',
  '720',
  'F10 21P3032938',
  '',
  '24000',
  '',
  '293.200',
  '289.100'],
 ['', '', '', '', '', '', 'PALLET WT', '48.500', ''],
 ['20',
  'SM100T',
  '720',
  'M10 21P3031869',
  '',
  '24000',
  'Total:',
  '635.500',
  '578.800'],
 ['20',
  'SM100T',
  '720',
  'M10 21P3032926',
  '',
  '24000',
  '',
  '292.800',
  '288.700'],
 ['',
  'SM100T',
  '720',
  'M10 21P3032926',
  '',
  '24000',
  '',
  '293.600',
  '289.500'],
 ['', '', '', '', '', '', 'PALLET WT', '48.500', ''],
 ['21',
  'SM100T',
  '720',
  'M10 21P3031860',
  '',
  '',
  'Total:',
  '634.900',
  '578.200'],
 ['21',
  'SM100T',
  '720',
  'F1021P3032929',
  '',
  '24000',
  '',
  '294.200',
  '290.100']

In [43]:
import pandas as pd
pd.DataFrame(out_array).to_csv('sample.csv')

In [44]:
df=pd.DataFrame(out_array)
df

0             1           2  \
0                                            
1     Pallet No.        SM100T  Width (MM)   
2             19        SM100T         720   
3                       SM100T         720   
4                                            
5             20        SM100T         720   
6             20        SM100T         720   
7                       SM100T         720   
8                                            
9             21        SM100T         720   
10            21        SM100T         720   
11                      SM100T         720   
12                                           
13            22        SM100T         720   
14            22        SM100T         720   
15                      SM100T         720   
16                                           
17            23        SM100T         750   
18            23        SM100T         750   
19                      SM100T         750   
20                                           
21            24        SM100T         750   
22            24        SM100T         750   
23                      SM100T         750   
24                                           
25                      SM100T        1385   
26                      SM100T        1385   
27                      SM100T        1385   
28                                           
29            26        SM100T         650   
30                      SM100T         650   
31                                           
32            27        SM100T         650   
33                      SM100T         650   
34                                           
35            28        SM100T         620   
36            28        SM100T         620   
37                      SM100T         620   
38                                           
39                      SM100T         700   
40            29        SM100T         700   
41                      SM100T         700   
42                                           
43            30        SM100T         700   
44            30        SM100T         700   
45                      SM100T         700   
46                                           
47                      SM100T         700   
48            31        SM100T         700   
49                      SM100T         700   
50                                           
51                                           
52                                           
53  Declaration:  Declaration:               
54                                           

                                                    3                  4  \
0                               DESCRIPTION OF GOODS.                      
1                                            Roll No.   Pallet Dimension   
2                                      M10 21P3032935                      
3                                      F10 21P3032938                      
4                                                                          
5                                      M10 21P3031869                      
6                                      M10 21P3032926                      
7                                      M10 21P3032926                      
8                                                                          
9                                      M10 21P3031860                      
10                                      F1021P3032929                      
11                                      F1021P3032929                      
12                                                                         
13                                                                         
14                                     D10 21P3034901                      
15                                     D10 21P3034901                      
16                                                                         
17                                     F10 21P3034902                 